accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('delete/',views.delete,name='delete'),
    path('update/',views.update,name='update'),
    path('password/',views.change_password,name='change_password'),
    path('',views.index,name='index'),
    path('<username>/', views.profile,name="profile"),
    path('<int:user_pk>/follow/',views.follow,name='follow')
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    # create 이름 변경 
    # path('new/', views.create, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/',views.comments_create,name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/',views.comments_delete,
    name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('ajax/',views.ajax,name='ajax')
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class User(AbstractUser) :
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings
# Create your models here.

class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    # image = models.ImageField(upload_to='images/',blank=True)
    image = ProcessedImageField(
        blank=True,
        upload_to='thumbnails/',
        processors=[Thumbnail(200, 300)],
        format='JPEG',
        options={'quality': 60})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

#댓글 
class Comment(models.Model) :
    #게시글 참조 on_delete를 이용해 게시글이 삭제되면 댓글도 자동 삭제되게 설정
    # 참조하는 모델과 1:N 관계일 때, 소문자 단수형으로 사용
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self) :
        return self.content

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm,UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserChangeForm(UserChangeForm) :

    class Meta :
        #USER Class
        model = get_user_model()
        fields = ('email','first_name','last_name')


class CustomUserCreationForm(UserCreationForm) :

    class Meta :
        # 현재 장고 프로젝트에서 활성화된 유저
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)

accounts/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm,PasswordChangeForm
# Create your views here.
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_http_methods,require_POST,require_safe
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash,get_user_model
from .forms import CustomUserCreationForm



@require_http_methods(['GET','POST'])
def login(request) :
    # 로그인 되어있으면 로그인 못하게 
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST' :
        #AuthenticationForm은 첫번째 인자로 request를 바음 
        form = AuthenticationForm(request,request.POST)
        if form.is_valid() :
            #인증이 되었다면 로그인 진행
            user = form.get_user()
            auth_login(request,user)
            return redirect(request.GET.get('next') or 'articles:index')
    
    else :
        #장고의 built-in login_form
        form = AuthenticationForm()

    context = {
        'form' : form,
    }
    return render(request,'accounts/login.html',context)


@require_POST
def logout(request):
    if request.user.is_authenticated : 
        auth_logout(request)
    return redirect('articles:index')

@require_http_methods(['GET','POST'])
def signup(request) :
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST' :
        form=CustomUserCreationForm(request.POST)
        if form.is_valid() :
            user = form.save()
            auth_login(request,user)
            return redirect('articles:index')
    else :
        form = CustomUserCreationForm()
        
    context = {
        'form' :form,
    }
    return render(request, 'accounts/signup.html',context)


@require_POST
def delete(request) :
    if request.user.is_authenticated:
        #반드시 회원 탈퇴 후 로그아웃 함수 호출 
        request.user.delete()
        auth_logout(request)
    return redirect('articles:index')

@login_required
@require_http_methods(["GET","POST"])
def update(request) :
    if request.method == 'POST' :
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid() :
            form.save()
            return redirect('articles:index')
    else :
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form,
    }
    return render(request,'accounts/update.html',context)

@login_required
def change_password(request) :

    if request.method == 'POST' :
        form = PasswordChangeForm(request.user,request.POST) 
        if form.is_valid() :
            form.save()
            # auth_login(request,form.save())
            update_session_auth_hash(request,form.save())
            return redirect('articles:index')
    else :
        form = PasswordChangeForm(request.user)
    
    context= {
        'form' : form,
    }

    return render(request, 'accounts/change_password.html',context)

@require_safe
def index(request) :
    User = get_user_model()
    users = User.objects.all()

    context = {
        'users':users
    }
    return render(request,'accounts/index.html',context)



def profile(request,username) :
    person = get_object_or_404(get_user_model(),username=username)
    context = {
        'person' : person,
    }

    return render(request, 'accounts/profile.html',context)

def follow(request,user_pk) :
    if  request.user.is_authenticated :
        me = request.user
        you = get_object_or_404(get_user_model(),pk=user_pk)
        if me!=you :
            if request.user in you.followers.all() :
                you.followers.remove(me)
                followed = False 
            else :
                you.followers.add(me)
                followed = True
            context = {
                'followed' :followed,
                'follower_cnt' : you.followers.count(),
                'following_cnt' : you.followings.count(),
            }
        return JsonResponse(context)
    return redirect('accounts:login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}

  <h1>비밀번호 변경</h1>
  <hr>
  <form action="{% url 'accounts:change_password' %}" method='POST'>

    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit">
  </form>
  <a class="btn btn-warning" href="{% url 'articles:index' %}">back</a>
{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}


{% block content %}
  <h1>userlist</h1>
  {% for user in users %}
    유저 {{user.pk}} : {{user}}
    <hr>
  {% endfor %}

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load socialaccount %}
{% block content %}


<h1>로그인</h1>
<form action="" method="POST">

  {% csrf_token %}
  {% bootstrap_form form%}
  <input type="submit" value="로그인하기" class="btn btn-primary">
</form>
<a href="{% provider_login_url 'google' next='/articles/'%}">[GOOGLE LOGIN]</a>
<a class="btn btn-warning" href="{% url 'articles:index' %}">back</a>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ person.username}}님의 프로필</h1>
  <hr>
  <div id="follow-cnt">
    팔로워 : {{person.followers.all|length}} |팔로우 : {{person.followings.all|length}} |
    <hr>
  </div>
    날 팔로우 하는 사람  : 
    {% for person in person.followers.all  %}
      {{person}}
    {% endfor %}
    |
    팔로잉 하는 사람  : 
   
    {% for person in person.followings.all  %}      
      {{person}}
    {% endfor %}
    <hr>
  <div>
    {% if user != person %}
      <form data-person-pk = "{{person.pk}}" id="follow_form" >
        {% if user in person.followers.all %}
          <button class="btn btn-primary" id="follow-button">언팔</button>
        {% else %}
          <button class="btn btn-danger" id="follow-button">팔로우</button>
        {% endif %}

      </form>
    {% endif %}
  </div>

  {% comment %} 작성한 게시글 {% endcomment %}
  <h2>{{person.username}}이 작성한 게시글</h2>

  {% for article in person.article_set.all  %}
    <p>{{article.title}}</p>
  {% endfor %}

  {% comment %} 작성한 댓글 {% endcomment %}
  <h2>{{person.username}}이 작성한 댓글</h2>
  {% for comment in person.comment_set.all %}
    <p>{{comment.content}}</p>
  
  {% endfor %}
  {% comment %} 좋아요를 누른 게시물  {% endcomment %}
  <h2>{{person.username}}이 좋아요를 누른 게시글</h2>
  {% for article in person.like_articles.all %}
    <p>{{article.title}}| 게시글의 좋아요 수 :{{ article.like_users.all | length }} </p>
  {% endfor %}
  <a class="btn btn-warning" href="{% url 'articles:index' %}">back</a>

  {% comment %} <script src="https://unpkg.com/axios/dist/axios.min.js"></script> {% endcomment %}
  <script>
    const form = document.querySelector('#follow_form')
    const personPk = form.dataset.personPk
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    // console.log(form.dataset.personPk)
    form.addEventListener('submit',function(event){
      event.preventDefault()
      axios({
        method : 'post',
        url : `/accounts/${personPk}/follow/`,
        headers: {
          'X-CSRFToken' : csrftoken
        },
      })
      .then(res => {
        const followed = res.data.followed
        // console.log(res)
        const button = document.querySelector('#follow-button')
        if (followed === true) {
          button.innerText = '언팔'
          button.setAttribute('class','btn btn-primary')
        }else{
          button.innerText = '팔로우'
          button.setAttribute('class','btn btn-danger')
        }
        // console.log(res.data)
        const followCnt = document.querySelector('#follow-cnt')
        const followingCnt = res.data.following_cnt
        const follwerCnt = res.data.follower_cnt
        followCnt.innerText = `팔로워 : ${follwerCnt} |팔로우 : ${followingCnt} |`
        const hr = document.createElement('hr')
        followCnt.append(hr)
      })
      // axios.post(`/accounts/${personPk}/follow/`)
      // .then(res=>{
      //   console.log(res)
      // })
    })
  </script>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <h1>회원가입</h1>
  <hr>
  <form action="{% url 'accounts:signup' %}" method='POST'>

    {% csrf_token %}
    {% bootstrap_form form%}
    <input class="btn btn-primary" type="submit">
  </form>
  <a class="btn btn-warning" href="{% url 'articles:index' %}">back</a>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <h1>회원정보 수정</h1>
  <hr>
  <form action="{% url 'accounts:update' %}" method='POST'>

    {% csrf_token %}
    {% bootstrap_form form%}
    <input class="btn btn-primary" type="submit">
  </form>
  <a class="btn btn-warning" href="{% url 'articles:index' %}">back</a>
{% endblock content %}