accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('delete/',views.delete,name='delete'),
    path('update/',views.update,name='update'),
    path('password/',views.change_password,name='change_password'),
    path('',views.index,name='index'),
    path('<username>/', views.profile,name="profile"),
    path('<int:user_pk>/follow/',views.follow,name='follow')
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    # create 이름 변경 
    # path('new/', views.create, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/',views.comments_create,name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/',views.comments_delete,
    name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('ajax/',views.ajax,name='ajax')
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings
# Create your models here.

class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    # image = models.ImageField(upload_to='images/',blank=True)
    image = ProcessedImageField(
        blank=True,
        upload_to='thumbnails/',
        processors=[Thumbnail(200, 300)],
        format='JPEG',
        options={'quality': 60})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

#댓글 
class Comment(models.Model) :
    #게시글 참조 on_delete를 이용해 게시글이 삭제되면 댓글도 자동 삭제되게 설정
    # 참조하는 모델과 1:N 관계일 때, 소문자 단수형으로 사용
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self) :
        return self.content

articles/forms.py
from django import forms

from articles.models import Article,Comment

class ArticleForm(forms.ModelForm) :
    # 장고 모델을 참고해서 form을 만들어줌 
    
    # input에 속성을 넣으려면 widget 내부 attribute에 작성을 해야한다.
    title = forms.CharField(
        widget=forms.TextInput(
            # attributes
            attrs = {
                'class' : 'my-title form-control',
                'placeholder':'Enter the title',

            }
        )
    )
    content = forms.CharField(
        widget = forms.Textarea(
            attrs={
                'class' : 'my-content form-control',
                'placeholder' :'Enter the content',

            }
        ),
        error_messages={
            'required' : 'Please enter your content!!!!!',
        }
    )
    class Meta :
        model = Article
        # 전체 필드 출력하는 __all__
        # fields = '__all__'
        exclude = ('user','like_users',)

# updateform을 만들 때 제목은 변경 못하게 하고 싶다면,
#기존 사용하던 createform을 상속 받은 후 
#원하느 필드를 읽기전용으로 만들거나 작동하지 않게 만듬 
class Article_updateForm(ArticleForm) :
    def __init__(self,*args,**kwargs) :
        super().__init__(*args,**kwargs)

        # self.fields['title'].widget.attrs['readonly'] = True
        
        # self.fields['content'].disabled = True

class CommentForm(forms.ModelForm) :

    class Meta :
        model = Comment
        fields = ('content',)

articles/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect,get_object_or_404

from articles import seriallizers
from .forms import Article_updateForm, ArticleForm,CommentForm
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .models import Article,Comment
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .seriallizers import ArticleSeriallizer
# Create your views here.
@require_safe
def index(request):
    articles = Article.objects.order_by('-pk')
    paginator = Paginator(articles,2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'articles': page_obj,
    }
    return render(request, 'articles/index.html', context)

@api_view(['GET'])
def ajax(request) :
    articles = Article.objects.order_by('-pk')
    paginator = Paginator(articles,2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    seriallizer = ArticleSeriallizer(page_obj,many=True)
    return Response(seriallizer.data)

# 요청에 따라 실행을 구분하고 new와 create 함수 합치기 
@login_required
def create(request):
    if request.method == 'POST' :
        form = ArticleForm(request.POST, request.FILES)
        #form에서 전달한 데이터가 유효하면 저장하고 detail을 redircet해라
        if form.is_valid() :
            # form.save()를 하면 생성된 객체를 리턴한다.
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail',article.pk)

    else :
        form = ArticleForm()
    context = {
        'form' : form,
    }
    # 유효성 검사를 통과하지 못하면 form은 에러메시지를 담고 있다. 그래서 에러메시지를 출력한다. 
    return render(request, 'articles/form.html',context)

#GET과 POST만 허용한다. 아니면 405에러 리턴 
@login_required
@require_http_methods(['GET','POST'])
def update(request, pk):
    article = get_object_or_404(Article,pk=pk)
    if request.user == article.user :
        if request.method == 'POST' : 
            # instacne=article을 안써주면 새로운 글을 만든다. 
            form = ArticleForm(request.POST, request.FILES,instance=article)
            if form.is_valid() :
                article=form.save()
                return redirect('articles:detail', article.pk) 
        else :
            # 기존 정보를 받아서 update.html을 표시하기 
            form = ArticleForm(instance=article)
    else :
        return redirect('articles:index')
    context = {
        'article' : article,
        'form': form
    }
    return render(request, 'articles/form.html', context)

@require_safe
def detail(request, pk):
    # article = Article.objects.get(pk=pk)
    # 객체가 있으면 객체를 없으면 404에러를 담아서 반환 
    article = get_object_or_404(Article,pk=pk)
    comment_form = CommentForm()
    # 조회한 article에 모든 댓글을 조회 
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form' : comment_form,
        'comments' : comments
    }
    return render(request, 'articles/detail.html', context)

@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article,pk=pk)
        if request.user == article.user :
            article.delete()
    return redirect('articles:index')


@require_POST
def comments_create(request,pk) :
    if request.user.is_authenticated :
        article = get_object_or_404(Article,pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid() :
            # commit의 기본값은 true이다. commit을 False로 바꿔서 DB에 저장은 안하고 인스턴스는 만들어줌 
            comment = comment_form.save(commit=False)
            # 누락된 article입력 해주고 
            comment.article = article
            comment.user = request.user
            #세이브 해줌 
            comment.save()
        return redirect('articles:detail',article.pk)
    return redirect('accounts:login')

@require_POST
def comments_delete(request,article_pk,comment_pk) :
    if request.user.is_authenticated :
        comment = get_object_or_404(Comment,pk=comment_pk)
        # article_pk = comment.article.pk
        if request.user == comment.user :
            comment.delete()
        return redirect('articles:detail',article_pk)
    return redirect('accounts:login')


def likes(request,article_pk) :
    #어떤 객체에 좋아요가 눌렸는지 확인
    article = get_object_or_404(Article, pk=article_pk)
    #누르는게 무조건 좋아요를 활성화하는 것은 아님 좋아요를 2번 누르면 취소되게 구현할 수 있음
    
    #이 게시글에 좋아요를 누른 유저 목록에 현재 요청하는 유저가 있다면 좋아요 취소 
    ##2가지 방법으로 조회 가능 
    if article.like_users.filter(pk=request.user.pk).exists() :
    # if request.user in article.like_users.all() : 
        article.like_users.remove(request.user)
        liked = False 
    #아니면 좋아요
    else :
        article.like_users.add(request.user)
        liked = True 
    context = {
        'liked' : liked,
        'like_count' : article.like_users.count()
    }
    return JsonResponse(context)
    # return redirect('articles:index')

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <br>
  {{request.resolver_match}}
  <h1>CREATE</h1>
  <hr>
  
  <form action="{% url 'article:create' %}" method="POST" enctype="multipart/form-data">
    {% comment %} form에서 url을 안넣어줘도 어차피나한테 와서 상관 없지만 명시해주는게 좋다.{% endcomment %}
    {% csrf_token %}
    {{form.as_p}}
    {% comment %} <label for="title">Title: </label>
    <input type="text" id="title" name="title"><br>
    <label for="content">Content: </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea> {% endcomment %}
    <input type="submit">
  </form>

  <h2>1. Rendering fields manually</h2>
  <form action="{% url 'articles:create' %} " method="POST">
    {% csrf_token %}

    <div>
      {{form.title.errors}}
      {{form.title.label_tag}}
      {{form.title}}
    </div>
    <div>
      {{form.content.errors}}
      {{form.content.label_tag}}
      {{form.content}}
    </div>
    <input type="submit">
  </form>
  <hr>
  <h2>2. Looping over the form's fields</h2>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}

    {% for field in  form%}
      {% if field.errors %}
        {% for error in field.errors %}
          <div class="alert alert-danger">{{error}}</div>
        {% endfor %}
      {% endif %}
      {{field.errors}}
      {{field.label_tag}}
      {{field}}
    {% endfor %}
    <input type="submit">
  </form>
  <a href="{% url 'articles:index' %}">back</a>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <h3>{{ article.pk }}번째 글</h3>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="사진 대기중">
  {% endif %}
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성 시각 : {{ article.created_at }}</p>
  <p>수정 시각 : {{ article.updated_at }}</p>
  {% if request.user == article.user %}
    <hr>
    <a href="{% url 'articles:update' article.pk %}">수정</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제">
    </form>
    <a href="{% url 'articles:index' %}">back</a>
  {% endif %}
  <hr>

  <h4>댓글 목록</h4>
  {% if comments %}
    <p><b>{{comments|length}}개의 댓글이 있습니다.</b></p>
  {% endif %}
  {% for comment in article.comment_set.all %}
    <li>
      {{comment.user}}-{{comment.content}}
      {% if request.user == comment.user %}
      <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
      </form>
      {% endif %}
    </li>
  {% endfor %}
  <hr>
  <h3>댓글</h3>
  {% if request.user.is_authenticated %}
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">댓글을 작성하려면 로그인 하세요 ^^</a>
  {% endif %}
{% endblock content %}

articles/templates/articles/edit.html
{% extends 'base.html' %}


{% block content %}
  <h1>EDIT</h1>
  <hr>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">Title: </label>
    <input type="text" id="title" name="title" value="{{ article.title }}"><br>
    <label for="content">Content: </label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea>
    <input type="submit">
  </form>
  <a href="{% url 'articles:detail' article.pk %}">back</a>
{% endblock content %}

articles/templates/articles/form.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block content %}
{% comment %} url이 create이면  {% endcomment %}
  {% if request.resolver_match.url_name == 'create' %}
    <h1>CREATE</h1>
  {% else %}
  {% comment %} edit이면  {% endcomment %}
    <h1>EDIT</h1>
  {% endif %}
  <hr>
  <form action="" method="POST"enctype="multipart/form-data" >
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} {{form.as_p}} {% endcomment %}
    <input type="submit">
  </form>

  {% if request.resolver_match.url_name == 'create' %}
  {% comment %} url이 crate면 메인으로 가는 back 만들기 {% endcomment %}
  <a href="{% url 'articles:index' %}">back</a>
  {% else %}
  <a href="{% url 'articles:index' %}">Home</a>
  <a href="{% url 'articles:detail' article.pk  %}">back</a>
  {% endif %}
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>Articles</h1>
  {% if request.user.is_authenticated %}
    <a href="{% url 'articles:create' %}">CREATE</a>
  {% else %}
    <a href="{% url 'accounts:login' %}?next=/articles/create/">[새 글을 작성하려면 로그인 하세요]</a>

  {% endif %}

  <hr>           
  {% for article in articles %}
    <p>작성자 : <a href="{% url 'accounts:profile' article.user%} ">{{article.user}}</a> </p>
    <p>글 번호: {{ article.pk }}</p>  
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <div id = "articleDiv">
      <form class="like-form" data-article-pk = "{{article.pk}}">
        {% if user in article.like_users.all %}
        <button  class="btn" style="background-color : transparent; padding: 0;">
          <i id="input-{{article.pk}}" class="fa solid fa-heart" style="color:red"></i>
        </button>
        {% else %}
        <button class="btn" style="background-color : transparent; padding: 0;">
          <i id="input-{{article.pk}}" class="fa regular fa-heart" ></i>
        </button>
        {% endif %}
      </form>
      <p id="cnt-{{article.pk}}">좋아요 수 : {{article.like_users.all|length}}</p>
    </div>

    <a href="{% url 'articles:detail' article.pk %}">DETAIL</a>
    <hr>
  {% endfor %} 

  <div class="pagination d-flex justify-content-center">
    {% bootstrap_pagination articles %}
  </div>

{% endblock content %}

{% block script %}
<script>
  const forms = document.querySelectorAll('.like-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  forms.forEach(form => {
    form.addEventListener('submit',function(event){
      event.preventDefault()
      const articlePk = event.target.dataset.articlePk
      // console.log(articlePk)
      axios({
        method : 'post',
        url : `/articles/${articlePk}/likes/`,
        headers : {
          'X-CSRFToken' : csrftoken
        },
      })
      .then(res => {
        // console.log(res)
        const liked = res.data.liked
        const likedCnt = res.data.like_count
        const likeCnt = document.querySelector(`#cnt-${articlePk}`)
        likeCnt.innerText = `좋아요 수 : ${likedCnt}`
        const input = document.querySelector(`#input-${articlePk}`)
        input.setAttribute("class","fa solid fa-heart")
        if (liked ===true){
          input.setAttribute("style","color:red")
        }else {
          input.setAttribute("style","color:black")
        }
      })
  })
})
</script>


<script>
  let page = 2 
  const articleDiv = document.querySelector('#articleDiv')

  document.addEventListener('scroll', function(event){
    const {scrollTop, clientHeight, scrollHeight} = document.documentElement
    if ((clientHeight + scrollTop) >= scrollHeight-5) {
      axios({
        method : 'get',
        url : `/articles/ajax/?page=${page}`
      })
      .then(res => {
        const articles = res.data
        articles.forEach(article => {
          console.log(article.title)
        })
        page++
      })
      .catch(err => console.error(err))
    }
  })
</script>
{% endblock script %}

articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>NEW</h1>
  <hr>
  
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <h1 style=""></h1>
    {{form.as_p}}
    {% comment %} <label for="title">Title: </label>
    <input type="text" id="title" name="title"><br>
    <label for="content">Content: </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea> {% endcomment %}
    <input type="submit">
  </form>
  <a href="{% url 'articles:index' %}">back</a>
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>EDIT</h1>
  <hr>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form%}
    {% comment %} {{form.as_p}} {% endcomment %}
    <input type="submit">
  </form>
  <a href="{% url 'articles:detail' article.pk %}">back</a>
{% endblock content %}